AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that writes to DynamoDB.
Resources:
  bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/store-consumption.zip
      Handler: com.gentrack.meter.consumption.lambda.CsvConsumptionHandler
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          WRITE_BATCH_SIZE: 150
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess # TODO set to read access only
      Tracing: Active
      Layers:
        - !Ref libs
      Events:
        s3Notification:
          Type: S3
          Properties:
            Bucket: !Ref bucket
            Events: s3:ObjectCreated:*
  Consumption:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: date
          AttributeType: S
        -
          AttributeName: meter
          AttributeType: S
        -
          AttributeName: value
          AttributeType: N
      KeySchema:
        -
          AttributeName: date
          KeyType: HASH
        -
          AttributeName: meter
          KeyType: RANGE
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: store-consumption-lib
      Description: Dependencies for the store consumption app.
      ContentUri: build/store-consumption-lib.zip
      CompatibleRuntimes:
        - java8

# TODO not sure if that is supported by AWS::Serverless-2016-10-31
Outputs:
  Consumption:
    Description: Table Created using this template.
    Value: !Ref Consumption